"""FlyCommander physical-table mode — event model.

Everything that changes state is an Event. Two origins:
  - "vision"   candidate events generated by the observer/tracker
               (reconciled, possibly down-weighted or rejected)
  - "player"   explicit human corrections via the UI/CLI (authoritative)

All events append to a log with timestamps and turn numbers.
"""
from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

EVENT_TYPES = frozenset({
    # object lifecycle
    "card_registered", "entered_battlefield", "left_battlefield",
    "zone_change", "moved", "appeared", "disappeared", "reappeared",
    # tapping
    "card_tapped", "card_untapped",
    # counters / modifiers / abilities
    "counter_added", "counter_removed", "temp_buff", "temp_debuff",
    "ability_granted", "ability_removed", "status_set", "damage_marked",
    "damage_cleared", "pt_set",
    # tokens
    "token_created", "token_removed",
    # combat
    "combat_begin", "combat_end", "attack_declared", "block_declared",
    "attack_retracted", "block_retracted", "combat_damage",
    # turns / phases
    "turn_advanced", "phase_changed", "untap_step",
    # players
    "life_changed", "poison_changed", "commander_damage",
    # stack
    "spell_cast", "spell_resolved",
    # registration
    "registration_started", "registration_failed", "identity_corrected",
    # reconciliation
    "candidate_rejected",
})

# vision events that must be confirmed by the player before mutating state
VISION_CONFIRM_REQUIRED = frozenset({
    "zone_change", "left_battlefield", "combat_damage", "attack_declared",
    "block_declared",
})


@dataclass
class Event:
    type: str
    origin: str                    # "vision" | "player" | "system"
    payload: dict[str, Any] = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)
    turn: int = 0
    confidence: float = 1.0
    note: str = ""

    def validate(self) -> None:
        if self.type not in EVENT_TYPES:
            raise ValueError(f"unknown event type: {self.type}")
        if self.origin not in ("vision", "player", "system"):
            raise ValueError(f"unknown event origin: {self.origin}")

    def describe(self) -> str:
        p = self.payload
        t = time.strftime("%H:%M:%S", time.localtime(self.timestamp))
        obj = p.get("name") or p.get("trackingId", "")
        if self.type == "card_tapped":
            body = f"{obj}: untapped → tapped"
        elif self.type == "card_untapped":
            body = f"{obj}: tapped → untapped"
        elif self.type == "counter_added":
            body = f"{obj}: +{p.get('amount', 1)} {p.get('counter', '')} counter"
        elif self.type == "counter_removed":
            body = f"{obj}: −{p.get('amount', 1)} {p.get('counter', '')} counter"
        elif self.type == "entered_battlefield":
            body = (f"{obj} entered battlefield"
                    + (" (summoning sick)" if p.get("summoningSick") else ""))
        elif self.type == "zone_change":
            body = f"{obj}: {p.get('from', '?')} → {p.get('to', '?')}"
        elif self.type == "life_changed":
            who = p.get("player", "?")
            delta = p.get("delta", 0)
            body = f"{who} life {'+' if delta >= 0 else ''}{delta} → {p.get('life', '?')}"
        elif self.type == "attack_declared":
            body = f"{obj} attacks {p.get('target', '?')}"
        elif self.type == "block_declared":
            body = f"{obj} blocks {p.get('attacker', '?')}"
        elif self.type == "temp_buff" or self.type == "temp_debuff":
            sign = "+" if self.type == "temp_buff" else "−"
            body = (f"{obj}: {sign}{abs(p.get('power', 0))}/{sign}"
                    f"{abs(p.get('toughness', 0))} until {p.get('expires', '?')}")
        elif self.type == "ability_granted":
            body = f"{obj}: gains {p.get('ability', '?')}"
        elif self.type == "ability_removed":
            body = f"{obj}: loses {p.get('ability', '?')}"
        elif self.type == "token_created":
            body = f"{p.get('count', 1)}× {p.get('tokenType', '?')} token created"
        elif self.type == "combat_damage":
            body = f"combat damage: {p.get('amount', 0)} to {p.get('target', '?')}"
        elif self.type == "turn_advanced":
            body = f"turn {p.get('turn', '?')} — {p.get('activePlayer', '?')}"
        elif self.type == "pt_set":
            body = f"{obj}: P/T set to {p.get('power')}/{p.get('toughness')}"
        elif self.type == "card_registered":
            body = (f"{p.get('name', '?')} registered"
                    f" ({p.get('set', '?')} #{p.get('collectorNumber', '?')})"
                    f" → {p.get('zone', 'battlefield')}")
        elif self.type == "appeared":
            body = f"{obj} visible"
        elif self.type == "disappeared":
            body = f"{obj} occluded ({p.get('frames', 1)} frames)"
        elif self.type == "moved":
            body = f"{obj} moved"
        else:
            body = self.note or json.dumps(p, sort_keys=True)[:80]
        return f"{t}  {body}"


class EventLog:
    """Append-only event log with optional JSONL persistence."""

    def __init__(self, path: str | Path | None = None, maxlen: int = 5000) -> None:
        self.path = Path(path) if path else None
        self.maxlen = maxlen
        self.entries: list[Event] = []
        if self.path and self.path.exists():
            self._load()

    def append(self, event: Event) -> Event:
        event.validate()
        self.entries.append(event)
        if len(self.entries) > self.maxlen:
            self.entries = self.entries[-self.maxlen // 2:]
        if self.path:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with open(self.path, "a", encoding="utf-8") as f:
                f.write(json.dumps({
                    "ts": event.timestamp,
                    "turn": event.turn,
                    "type": event.type,
                    "origin": event.origin,
                    "confidence": round(event.confidence, 3),
                    "payload": event.payload,
                }) + "\n")
        return event

    def recent(self, n: int = 50, min_type: str | None = None) -> list[Event]:
        items = self.entries
        if min_type:
            items = [e for e in items if e.type == min_type]
        return list(items[-n:])

    def describe_recent(self, n: int = 20) -> list[str]:
        return [e.describe() for e in self.recent(n)]

    def _load(self) -> None:
        try:
            with open(self.path, encoding="utf-8") as f:
                for line in f:
                    d = json.loads(line)
                    self.entries.append(Event(
                        type=d["type"], origin=d.get("origin", "system"),
                        payload=d.get("payload", {}),
                        timestamp=d.get("ts", 0.0), turn=d.get("turn", 0),
                        confidence=d.get("confidence", 1.0)))
        except (json.JSONDecodeError, KeyError, OSError):
            self.entries = []
